[theme]
primaryColor="rgb(75, 204, 255)"
backgroundColor="rgb(245, 252, 255)"
secondaryBackgroundColor="rgb(223, 236, 255)"
textColor="rgb(37, 38, 48)"

font="sans serif"
[client]
showSidebarNavigation = false
[server]
runOnSave = true